// Generated by CoffeeScript 1.12.5

/*
 * nodejs-express-mongoose-demo
 * Copyright(c) 2013 Madhusudhan Srinivasa <madhums8@gmail.com>
 * MIT Licensed
 */


(function() {
  var _, app, compression, config, configs, debuglog, env, err, exports, express, externalConfig, fs, mongoose, p, path, pathToExternalConfig, pkg, port, https;

  express = require('express');

  compression = require('compression');
  //added
  // https = require('https');
  //
  fs = require('fs');

  p = require("commander");

  path = require("path");

 // _ = require("underscore");

  debuglog = require("debug")("ticketman:server");

  var session = require("client-sessions");

   //create HTTPS server added
// var options = { 
//   ca: fs.readFileSync( './ssl/__luminartech_com.ca-bundle' ),
//   key: fs.readFileSync( './ssl/luminartech_com.key' ),  
//   cert: fs.readFileSync( './ssl/certificate.crt' ),
// };

//   var server = https.createServer(options, app);
// app = https.createServer(options);
//

  pkg = JSON.parse(fs.readFileSync(path.join(__dirname, "../package.json")));

  p.version(pkg.version).option('-c, --config [VALUE]', 'path to config file').option('-p, --port [VALUE]', 'port to run this web service').option('-e, --environment  [VALUE]', 'application environment mode').parse(process.argv);

  env = p.environment || process.env.NODE_ENV || 'development';

  config = require('./config/config');

  configs = configs[env];

  config.version = pkg.version;

  config.root = path.resolve(__dirname, "../");

  debuglog("[server] config.root:" + config.root);

  if (p.config) {
    try {
      pathToExternalConfig = path.resolve(config.root, p.config);
      debuglog("pathToExternalConfig:" + pathToExternalConfig);
      externalConfig = JSON.parse(fs.readFileSync(pathToExternalConfig));
      debuglog("externalConfig:%j", externalConfig);
      _.extend(config, externalConfig);
    } catch (error) {
      err = error;
      debuglog("ERROR [server] fail to mixin externalConfig. " + err);
    }
  }

  mongoose = require('mongoose');

  mongoose.connect(config.db);
  
  if (env === 'development') {
    mongoose.set('debug', true);
  }

  require("./models/ticket");

  require("./models/worker");

  app = express();

  app.use(compression());

  require('./config/express')(app, config);

  require('./config/routes')(app);

  

  port = p.port || process.env.PORT || 3456;
  //added 
  // server.listen(port);
  
  //
  app.listen(port);

  debuglog("Ticketman app started on port " + port);

  exports = module.exports = app;

}).call(this);
